apiVersion: v1
kind: Pod
metadata:
  name: arm64-test
  labels:
    app: arm64-test
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi