apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: kube-system
data:
  aws.clusterEndpoint: "${CLUSTER_ENDPOINT}"  # Will be replaced by the setup script
  aws.defaultInstanceProfile: "KarpenterNodeInstanceProfile-${CLUSTER_NAME}"  # Will be replaced by the setup script
  aws.interruptionQueueName: "${CLUSTER_NAME}"  # Will be replaced by the setup script
  kubernetes.clusterName: "${CLUSTER_NAME}"  # Will be replaced by the setup script
  kubernetes.clusterCIDR: "10.0.0.0/16"  # VPC CIDR - adjust if your VPC uses a different CIDR